#!/usr/bin/env python
"""
script to copy mysql db from old location to new location
"""

import shutil, os, sys

SRC_DATA_DIR = "/usr/local/old-mysql-5.0.41-osx10.4-i686/data/"
DST_DATA_DIR = "/usr/local/mysql/data/"

for arg in sys.argv[1:]:
    dst = os.path.join(DST_DATA_DIR, arg)
    shutil.copytree(
            os.path.join(SRC_DATA_DIR, arg),
            dst 
            )
    os.system('chown -R _mysql %s' % dst)

